version: "3.9"
services:
  router01:
    image: mongo:latest
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27001:27017
    volumes:
      - .:/shared
  router02:
    image: mongo:latest
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - .:/shared
    ports:
      - 27002:27017

  configsvr01:
    image: mongo:latest
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - .:/shared
    ports:
      - 20101:27017
  configsvr02:
    image: mongo:latest
    container_name: mongo-config-02
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - .:/shared
    ports:
      - 20102:27017
  configsvr03:
    image: mongo:latest
    container_name: mongo-config-03
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - .:/shared
    ports:
      - 20103:27017

  shard01-a:
    image: mongo:latest
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - .:/shared
    ports:
      - 20011:27017
  shard01-b:
    image: mongo:latest
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - .:/shared
    ports:
      - 20012:27017
  shard01-c:
    image: mongo:latest
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - .:/shared
    ports:
      - 20013:27017

  shard02-a:
    image: mongo:latest
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - .:/shared
    ports:
      - 20021:27017
  shard02-b:
    image: mongo:latest
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - .:/shared
    ports:
      - 20022:27017
  shard02-c:
    image: mongo:latest
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - .:/shared
    ports:
      - 20023:27017

  shard03-a:
    image: mongo:latest
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - .:/shared
    ports:
      - 20031:27017
  shard03-b:
    image: mongo:latest
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - .:/shared
    ports:
      - 20032:27017
  shard03-c:
    image: mongo:latest
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - .:/shared
    ports:
      - 20033:27017

  rest:
    image: openjdk:11
    container_name: rest_api
    command: java -jar /shared/target/nosql-0.0.1-SNAPSHOT.jar
    volumes:
      - .:/shared
    ports:
      - 8080:8080
